version: '3.8'

services:
  app:
    build: .
    container_name: flask-portfolio
    env_file:
      - ./app/.env
    expose:
      - "5000"
    restart: always

  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
